// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app', ['ngRoute', 'ngMock']).controller('MainController', function($scope) {
    $scope.text = 'Hello World!';
    return $scope.passwordLength = function(password) {
      password = password.length;
      switch (false) {
        case !(password < 5):
          return "Short";
        case !(password > 10):
          return "Long";
        default:
          return "Just Right(?)";
      }
    };
  });

}).call(this);
