// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    main: function(req, res) {
      return res.render('home');
    },
    templates: function(req, res) {
      return res.render('templates/' + req.params.templateid);
    }
  };

}).call(this);
